### ISSUE TITLE
重构代码

### ISSUE THREAD

**Issue by ZhoBudweiser** [ZhoBudweiser/BusGo#15]
### 问题描述

先前为了快速实现功能，代码的组织不够清晰，需要重构为清晰完整的代码。

### 平台

- 操作系统: [iOS, Android, Harmony OS ...]
- 手机型号: [iPhone 15, HUAWEI Mate 60 Pro, Miaomi 14 ...]

**Comment by Yizhihuan22** [comment]
大佬，
